environment: canary

replicaCount: 1
backend: #http://backend-podinfo-dev:9898/echo
backends: []

# metrics-server add-on required
hpa:
  enabled: false

# Redis deployment
redis:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 32Mi
