sonarqubeUsername: admin
sonarqubePassword: Changeme555

minHeapSize: 768m
maxHeapSize: 1520m

resources:
  requests:
    memory: "2.5Gi"

sysctl:
  enabled: false

postgresql:
  enabled: false

##connect to PostGres using cloud-sql-proxy sidecar container
externalDatabase:
  host: "127.0.0.1"
  user: postgres
  password: "Password555!"

serviceAccount:
  create: false
  name: sonarqube-sa

sidecars:
  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
    imagePullPolicy: Always
    args:
      - "--structured-logs"
      - "--port=5432"
      - "silver-nova-120316:europe-west2:sonarqube-dev-ae9eba81"
    ports:
      - name: db-port
        containerPort: 5432
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "1"
