kind: Service
apiVersion: v1
metadata:
  name: gceme-backend-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.port }}
    protocol: TCP
  selector:
    role: backend
    app: gceme
    {{ if eq .Values.environment "canary" }}
    env: canary
    {{ end }}
