apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-dev
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  project: default
  source:
    path: helm-chart
    repoURL:  'https://github.com/vjkancherla/the_ideal_pipeline'
    helm:
      valueFiles:
        - namespaces/dev/values.yaml
        - namespaces/dev/version.yaml
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
